name: rook_sdk_demo_app_flutter
description: Demo app of rook_sdk packages
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rook_sdk_core: ^1.0.0
  rook_sdk_apple_health: ^1.7.0
  rook_sdk_health_connect: ^3.0.0
  app_settings: ^5.1.1
  receive_intent: ^0.2.5
  logging: ">=1.0.0 <2.0.0"
  shared_preferences: ^2.5.2
  url_launcher: ">=6.0.0 <7.0.0"
  focus_detector: ">=2.0.0 <3.0.0"
  flutter_dotenv: ^6.0.0
  dio: ^5.9.0
  fl_chart: ^1.0.0

  get: ^4.7.2
  freezed: ^2.5.7
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.4
  equatable: ^2.0.7
  freezed_annotation: ^2.4.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env.dev

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
